AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Transforms images by cropping
Resources:
  transform:
    Type: AWS::Serverless::Function
    Properties:
      Description: Transforms images by cropping
      Handler: src/index.handler
      Runtime: nodejs12.x
      CodeUri: build/transform.zip
      MemorySize: 1536
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: sourceBucket
        - S3CrudPolicy:
            BucketName:
              Ref: destBucket
      Timeout: 300
      Events:
        upload:
          Type: S3
          Properties:
            Bucket:
              Ref: source
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          DEST_BUCKET:
            Ref: destBucket
          WIDTH:
            Ref: width
          HEIGHT:
            Ref: height
          X_COORDINATE:
            Ref: xCoordinate
          Y_COORDINATE:
            Ref: yCoordinate
  source:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: sourceBucket
Parameters:
  sourceBucket:
    Type: String
    Description: Name of the S3 Bucket to read source images from (must NOT exist prior to deployment)
  destBucket:
    Type: String
    Description: Name of the S3 Bucket to put transformed images into (must exist prior to deployment)
  width:
    Type: Number
    Description: Width of cropped image
    Default: 600
  height:
    Type: Number
    Description: Height of cropped image
    Default: 400
  xCoordinate:
    Type: Number
    Description: (x, y) is the upper left corner of the cropped region
    Default: 50
  yCoordinate:
    Type: Number
    Description: (x, y) is the upper left corner of the cropped region
    Default: 50
