AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless photo gallery

Globals:
  Api:
    BinaryMediaTypes:
      - '*~1*'

Resources:
  galleria:
    Type: AWS::Serverless::Function
    Properties:
      Description: Serverless photo gallery
      Handler: src/index.handler
      Runtime: nodejs12.x
      CodeUri: build/package.zip
      MemorySize: 1536
      Policies:
        - S3ReadPolicy:
            BucketName:
              Ref: thumbBucket
        - S3ReadPolicy:
            BucketName:
              Ref: fullBucket
      Timeout: 60
      Events:
        root:
          Type: Api
          Properties:
            Path: /
            Method: get
        getProxy:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: get
      Environment:
        Variables:
          THUMB_BUCKET:
            Ref: thumbBucket
          FULL_BUCKET:
            Ref: fullBucket
Parameters:
  thumbBucket:
    Type: String
    Description: Name of the S3 Bucket from which to read the thumbnails (must exist prior to deployment)
  fullBucket:
    Type: String
    Description: Name of the S3 Bucket from which to read the full size images (must exist prior to deployment)
